<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=tools
 * [END_COT_EXT]
 */
 
/**
 * Shop
 *
 * @version 3.00
 * @author esclkm
 * @copyright (c) 2010 esclkm
 */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

if (!in_array($n, array('delivery', 'deliveryprices', 'payments')))
{
	$n = 'main';
}

if (file_exists(cot_incfile('shop', 'plug', 'admin.'.$n)))
{
	$t = new XTemplate(cot_tplfile('shop.admin.'.$n, 'plug'));
	require_once cot_incfile('shop', 'plug', 'admin.'.$n);
	$t->parse('MAIN');
	$adminmain = $t->text('MAIN');
}
else
{
	// Error page
	cot_die_message(404);
	exit;
}
